import json
from io import BytesIO

from app.models import EvidenceSignal


def inspect_c2pa(image_bytes: bytes, content_type: str) -> EvidenceSignal:
    try:
        import c2pa  # type: ignore
    except Exception:
        return EvidenceSignal(
            checked=False,
            status="unavailable",
            summary="c2pa-python is not installed or could not be imported.",
        )

    try:
        with c2pa.Reader(content_type, BytesIO(image_bytes)) as reader:
            manifest_json = reader.json()
    except Exception as exc:
        return EvidenceSignal(
            status="absent",
            summary="No readable C2PA manifest was found.",
            details={"reason": exc.__class__.__name__},
        )

    try:
        manifest = json.loads(manifest_json)
    except json.JSONDecodeError:
        manifest = {"raw": manifest_json}

    manifest_text = json.dumps(manifest, ensure_ascii=False).lower()
    ai_terms = [
        "aigc",
        "ai-generated",
        "generated by ai",
        "openai",
        "dall-e",
        "dalle",
        "gemini",
        "notebooklm",
        "imagen",
        "synthid",
        "nano banana",
        "midjourney",
    ]
    is_ai_related = any(term in manifest_text for term in ai_terms)
    active_manifest = manifest.get("active_manifest") if isinstance(manifest, dict) else None
    manifests = manifest.get("manifests", {}) if isinstance(manifest, dict) else {}
    active_data = manifests.get(active_manifest, {}) if isinstance(manifests, dict) else {}
    signature_info = active_data.get("signature_info", {}) if isinstance(active_data, dict) else {}
    assertions = active_data.get("assertions", []) if isinstance(active_data, dict) else []

    return EvidenceSignal(
        detected=True,
        status="detected",
        summary=(
            "C2PA manifest contains AI-related provenance terms."
            if is_ai_related
            else "C2PA manifest is present; no AI-related term was detected by v0 rules."
        ),
        details={
            "active_manifest": active_manifest,
            "manifest_count": len(manifests) if isinstance(manifests, dict) else None,
            "title": active_data.get("title") if isinstance(active_data, dict) else None,
            "format": active_data.get("format") if isinstance(active_data, dict) else None,
            "claim_generator": active_data.get("claim_generator") if isinstance(active_data, dict) else None,
            "claim_version": active_data.get("claim_version") if isinstance(active_data, dict) else None,
            "signature_issuer": signature_info.get("issuer") if isinstance(signature_info, dict) else None,
            "signature_common_name": signature_info.get("common_name") if isinstance(signature_info, dict) else None,
            "signature_time": signature_info.get("time") if isinstance(signature_info, dict) else None,
            "validation_state": manifest.get("validation_state") if isinstance(manifest, dict) else None,
            "validation_status": [
                item.get("code")
                for item in manifest.get("validation_status", [])
                if isinstance(item, dict) and item.get("code")
            ]
            if isinstance(manifest, dict)
            else [],
            "assertion_labels": [
                item.get("label")
                for item in assertions
                if isinstance(item, dict) and item.get("label")
            ],
            "ai_related": is_ai_related,
        },
    )
