// Heuristic C2PA reader for offline mode.
//
// This does NOT cryptographically verify the manifest. It detects whether a
// C2PA / JUMBF manifest is embedded, extracts best-effort source strings, and
// flags AI-related terms. Because no signature verification is possible without
// the C2PA toolkit, validation_state is always unknown in offline mode.

const latin1 = new TextDecoder("latin1");

const AI_TERMS = [
  "aigc",
  "ai-generated",
  "generated by ai",
  "openai",
  "dall-e",
  "dalle",
  "gemini",
  "notebooklm",
  "imagen",
  "synthid",
  "nano banana",
  "midjourney",
];

export function inspectC2pa(bytes) {
  const text = latin1.decode(bytes);
  const lower = text.toLowerCase();

  if (!hasManifest(lower)) {
    return {
      checked: true,
      detected: false,
      status: "absent",
      summary: "No readable C2PA manifest was found.",
      details: { reason: "NoReadableManifest" },
    };
  }

  const region = manifestRegion(text, lower);
  const regionLower = region.toLowerCase();
  const isAiRelated = AI_TERMS.some((term) => regionLower.includes(term));

  const claimGenerator = extractClaimGenerator(region);
  const assertionLabels = extractAssertionLabels(region);

  return {
    checked: true,
    detected: true,
    status: "detected",
    summary: isAiRelated
      ? "C2PA manifest contains AI-related provenance terms."
      : "C2PA manifest is present; no AI-related term was detected by v0 rules.",
    details: {
      active_manifest: null,
      manifest_count: null,
      title: null,
      format: null,
      claim_generator: claimGenerator,
      claim_version: null,
      signature_issuer: null,
      signature_common_name: null,
      signature_time: null,
      // Offline mode cannot verify the signature, so the state stays unknown.
      validation_state: null,
      validation_status: [],
      assertion_labels: assertionLabels,
      ai_related: isAiRelated,
      offline_unverified: true,
    },
  };
}

function hasManifest(lower) {
  if (lower.includes("c2pa.org") || lower.includes("urn:c2pa") || lower.includes("contentauth")) {
    return true;
  }
  // A JUMBF box carrying a c2pa label is the canonical embedding form.
  return lower.includes("jumb") && lower.includes("c2pa");
}

function manifestRegion(text, lower) {
  let start = lower.indexOf("jumb");
  if (start < 0) {
    start = lower.indexOf("c2pa");
  }
  if (start < 0) {
    return text;
  }
  const begin = Math.max(0, start - 64);
  return text.slice(begin, begin + 65536);
}

function extractClaimGenerator(region) {
  const strings = printableStrings(region);
  // claim_generator values look like "make_name/1.0" or "Adobe_Firefly 1.0".
  const versioned = strings.find((value) => /[A-Za-z][A-Za-z0-9._-]+\/[0-9][0-9A-Za-z._-]*/.test(value));
  if (versioned) {
    const match = versioned.match(/[A-Za-z][A-Za-z0-9._-]+\/[0-9][0-9A-Za-z._-]*/);
    return match ? match[0] : versioned.slice(0, 120);
  }
  const branded = strings.find((value) =>
    /(openai|adobe|truepic|google|gemini|imagen|notebooklm|midjourney|leica|nikon|sony|canon)/i.test(value),
  );
  return branded ? branded.slice(0, 120) : null;
}

function extractAssertionLabels(region) {
  const labels = new Set();
  const pattern = /c2pa\.[a-z0-9]+(?:[._-][a-z0-9]+)*/gi;
  let match;
  while ((match = pattern.exec(region)) !== null) {
    labels.add(match[0]);
    if (labels.size >= 24) {
      break;
    }
  }
  return [...labels];
}

function printableStrings(region) {
  const matches = region.match(/[\x20-\x7e]{4,}/g);
  return matches || [];
}
